"""
Reviewer: analyzes the code generated by the implementer and emits a verdict.

Role: pure code review. It does not execute anything. Tests are executed by
other deterministic phases. The reviewer looks for things an expert human
would notice: subtle bugs, security issues, clarity, maintainability.
"""
from __future__ import annotations

from pathlib import Path

from agents.base import BaseAgent
from agents.models import AgentResult, TaskInput


# The role definition lives in `agents/prompts/reviewer.md`. Edit that file
# (and rebuild the agent image) to tune behavior; do not inline a copy here.
SYSTEM_PROMPT = (
    Path(__file__).parent / "prompts" / "reviewer.md"
).read_text(encoding="utf-8")


class ReviewerAgent(BaseAgent):
    def __init__(self, task: TaskInput):
        super().__init__(task, SYSTEM_PROMPT)

    def build_user_prompt(self) -> str:
        parts = [
            f"# Original task\n\n{self.task.prompt}",
            f"\n# Branches\n- base: {self.task.base_branch}\n"
            f"- feature: {self.task.feature_branch}",
            "\nReview the changes. Start by calling get_diff.",
        ]
        return "\n".join(parts)


def run(task: TaskInput) -> AgentResult:
    return ReviewerAgent(task).run()
